### ISSUE TITLE
NetacadExamPlayer in 7.2

### ISSUE THREAD

**Issue by copart** [rpallai/flatpak-pt#3]
I installed 7.1 and it works!.... THANK YOU!

Curious:

Why is NetacadExamPlayer not supported in 7.2

**Comment by rpallai** [comment]
Because I'm not interested in running Exam Player. To tell you the truth, I've never tried to run it. Altough, Exam Player support would be merged if someone took the time to make a PR in order.

> Why is NetacadExamPlayer not supported in 7.2
